spring.application.name=neteasemusic

# analysis api
analysis.ip=127.0.0.1
analysis.port=5000

#download.path=${user.home}/neteasemusic-dl/
#download.path=/Users/zhoufan/Music/netease-dl/
xsdownload.path=/media/music/
#download.path=C:/develop/downloads/music/
#download.path=./downloads/music/


spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
